name: bookinghotel-fe
#113
applabels: bookinghotel-fe
#=====================
# DEPLOYMENT
#=====================
deployment:
  enabled: true
  image:
    name: bookinghotel-fe-container
    repository: bookinghotel_fe
    tag: "01"
    port: 120

  resources:
    enabled: false
    request:
      memory: 64Mi
      cpu: 250m
    limit:
      memory: 128Mi
      cpu: 500m

#======================
# SERVICE
#=====================
service:
  enabled: true

#======================
# INGRESS
#=====================
ingress:
  enabled: true
  domain: ""
  path: "/"

route:
  enabled: false

#======================
# CONFIGMAP
#=====================

configmap:
  enabled: true
  data:
    apiUrl: "http://localhost:3000"

#======================
# VOLUMES AND MOUNTVOLUMES
#======================
volumeMounts:
  enabled: true
  items:
    - name: fe-config-axios
      mountPath: /usr/share/nginx/html/env.js
      subPath: env.js

volumes:
  enabled: true
  items:
    - name: fe-config-axios 
      configMap:
        name: bookinghotel-fe-configmap

#======================
# SECRETS
#======================
secret:
  enabled: true
  portService: 80
  portTarget: 80

env:
  enabled: true
  items:
    - name: DB_HOST
      valueFrom:
        secretKeyRef:
          name: confighostdatabase-secret
          key: DB_HOST
          optional: false

    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: confighostdatabase-secret
          key: DB_USER
          optional: false

    - name: DB_PASS
      valueFrom:
        secretKeyRef:
          name: confighostdatabase-secret
          key: DB_PASS
          optional: false

    - name: DB_NAME
      valueFrom:
        secretKeyRef:
          name: confighostdatabase-secret
          key: DB_NAME
          optional: false

    - name: DB_PORT
      valueFrom:
        secretKeyRef:
          name: confighostdatabase-secret
          key: DB_PORT
          optional: false
extraSecrets:
  enabled: false

extraConfigMaps:
  enabled: false
#======================
# PVC
#======================
pvc:
  enabled: false

# 113
#456
