name: bookinghotel-be
#113
applabels: bookinghotel-be
#=====================
# DEPLOYMENT
#=====================

deployment:
  enabled: true
  image:
    name: bookinghotel-be-container
    repository: bookinghotel_be
    tag: "01"
    port: 120

  resources:
    enabled: false
    request:
      memory: 64Mi
      cpu: 250m
    limit:
      memory: 128Mi
      cpu: 500m
#======================
# SERVICE
#=====================
service:
  enabled: true

#======================
# INGRESS
#=====================
ingress: 
  enabled: false
  domain: ""
  path: ""

# Openshift
route:
  enabled: false

#======================
# CONFIGMAP
#=====================

configmap:
  enabled: false
#   nameConfigMap: orderservice-be-application-propertie-configmap
#   data:
#     server.port: "${PORT_SERVICE}"
#     spring.application.name: "${NAME_SERVICE}"


#======================
# VOLUMES AND MOUNTVOLUMES
#======================
volumeMounts:
  enabled: false

volumes:
  enabled: false



#======================
# SECRETS
#======================
secret:
  enabled: true
  portService: 80
  portTarget: 3000

env:
  enabled: true
  items:
    - name: DB_URL
      valueFrom:
        secretKeyRef:
          name: confighostdatabase-secret
          key: DB_URL
          optional: false      
  
extraSecrets:
  enabled: false
#======================
# PVC
#======================
pvc:
  enabled: false

# 113
#456