---
{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  env.js: |
    window.__ENV__ = {
      API_URL: "{{ .Values.configmap.data.apiUrl }}"
    };
{{- end }}